name: Deploy to Server

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Deploy to server
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          
          
          cd ~
          if [ ! -d ".git" ]; then
            git clone https://github.com/MrLampochka/CI-CD-Practice.git ./project
          fi
          cd project
          # Обновляем код
          git fetch --all
          git reset --hard origin/main
          
          # Останавливаем и перезапускаем контейнеры
          docker compose down
          docker compose up -d --build
          # Очистка неиспользуемых образов
          docker image prune -f
